### ISSUE TITLE
COD4 xmodels

### ISSUE THREAD

**Issue by henrikssonkevin** [AgenteDog/CoDtoUE4#1]
Hi

Had some problems when placing xmodels from COD4 in UE4.

Had to do the following changes to PlaceAssets():

```
actor_location = (float(info['PosX']) * 2.54) * -1, float(info['PosY']) * 2.54, float(info['PosZ']) * 2.54
                
actor_rotation = float(info['RotY']), float(info['RotZ']) * -1, float(info['RotX']) * -1
                
actor_scale = -(float(info['Scale'])), -(float(info['Scale'])), float(info['Scale'])
```

Works like a charm now.

Thanks a bunch for a great script!

**Comment by idanyekutiel** [comment]
Hey! I am happy it works now 👍 Question: What cod were you trying to use? What problems where you getting?
