### ISSUE TITLE
4.23 crashes when settings are correct when running plugin

### ISSUE THREAD

**Issue by emojimatt12** [AgenteDog/CoDtoUE4#5]
Whenever I try to run the plugin on 4.23 it crashes the engine. I've tried everything, read the docs about what makes it prone to crashing, updated my drivers, overclocked my laptop and tried other engine versions. None work even though I got the settings all correct. I used the fbx file instead of the obj and it still crashes.

**Comment by AgenteDog** [comment]
The plugin seems to not work for certain people. This might be related to their computer specs or something similar, I am not sure yet. Hopefully most of this issues will be fixed next update.

**Comment by emojimatt12** [comment]
I got an Nvidia Geforce GTX 1060
Intel(R) Core(TM) i7- 6700HQ CPU 
15.9 GB RAM 

I'm looking to upgrade my gaming laptop in a few months to a PC with a better graphics card but thanks I'm looking forward to the update so I can get it working
