### ISSUE TITLE
All assets are ? symbols

### ISSUE THREAD

**Issue by filmedbymatthew** [AgenteDog/CoDtoUE4#6]
Tried out the new updated plugin. While it works in the importing stage, neither the obj or fbx will import the assets as all of the xmodels are "?" symbols. It exports very quickly and I've tried different ways to get around this but all the assets are ? symbols. Map geometry and textures are black and pink checkered patterns

**Comment by idanyekutiel** [comment]
This means you probably put the wrong location of the greyhound folder, or your models are not in the folder, or very probably you named the fbx wrong.
